"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { X, Download } from "lucide-react"
import jsPDF from "jspdf"

interface Student {
  id: string
  name: string
  rollNo: string
  course: string
  year: string
  totalPoints: number
  documentsCount: number
}

interface MeritListModalProps {
  isOpen: boolean
  onClose: () => void
  students: Student[]
}

export default function MeritListModal({ isOpen, onClose, students }: MeritListModalProps) {
  const [sortedStudents, setSortedStudents] = useState<(Student & { rank: number })[]>([])

  // Generate ranked list
  const generateRankedList = () => {
    const ranked = [...students]
      .sort((a, b) => b.totalPoints - a.totalPoints)
      .map((student, index) => ({
        ...student,
        rank: index + 1,
      }))
    setSortedStudents(ranked)
  }

  const handleExportPDF = () => {
    generateRankedList()

    const doc = new jsPDF()
    const pageHeight = doc.internal.pageSize.getHeight()
    const pageWidth = doc.internal.pageSize.getWidth()
    let yPosition = 20

    // Title
    doc.setFontSize(16)
    doc.text("IQAC Merit List", pageWidth / 2, yPosition, { align: "center" })
    yPosition += 10

    // Date
    doc.setFontSize(10)
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, pageWidth / 2, yPosition, {
      align: "center",
    })
    yPosition += 15

    // Prepare data
    const ranked = [...students]
      .sort((a, b) => b.totalPoints - a.totalPoints)
      .map((student, index) => ({
        ...student,
        rank: index + 1,
      }))

    // Table headers
    const headers = ["Rank", "Name", "Roll No", "Course", "Points"]
    const columnWidths = [15, 50, 25, 50, 20]

    // Draw headers
    doc.setFontSize(10)
    doc.setFillColor(240, 240, 240)
    let xPosition = 10
    headers.forEach((header, i) => {
      doc.rect(xPosition, yPosition, columnWidths[i], 8, "F")
      doc.text(header, xPosition + 2, yPosition + 5, { maxWidth: columnWidths[i] - 4 })
      xPosition += columnWidths[i]
    })
    yPosition += 8

    // Draw rows
    doc.setFontSize(9)
    ranked.forEach((student) => {
      if (yPosition > pageHeight - 20) {
        doc.addPage()
        yPosition = 20
      }

      const row = [
        student.rank.toString(),
        student.name,
        student.rollNo,
        student.course,
        student.totalPoints.toString(),
      ]

      xPosition = 10
      row.forEach((cell, i) => {
        doc.text(cell, xPosition + 2, yPosition + 5, {
          maxWidth: columnWidths[i] - 4,
        })
        xPosition += columnWidths[i]
      })

      yPosition += 8
    })

    // Footer
    doc.setFontSize(8)
    doc.text("This is an official merit list generated by Maitreyi College IQAC", 10, pageHeight - 10)

    doc.save(`merit-list-${new Date().toISOString().split("T")[0]}.pdf`)
  }

  const handleExportCSV = () => {
    generateRankedList()

    const ranked = [...students]
      .sort((a, b) => b.totalPoints - a.totalPoints)
      .map((student, index) => ({
        ...student,
        rank: index + 1,
      }))

    const headers = ["Rank", "Name", "Roll No", "Course", "Year", "Total Points"]
    const rows = ranked.map((student) => [
      student.rank,
      student.name,
      student.rollNo,
      student.course,
      student.year,
      student.totalPoints,
    ])

    const csvContent = [headers.join(","), ...rows.map((row) => row.join(","))].join("\n")

    const blob = new Blob([csvContent], { type: "text/csv" })
    const url = window.URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `merit-list-${new Date().toISOString().split("T")[0]}.csv`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    window.URL.revokeObjectURL(url)
  }

  if (!isOpen) return null

  // Generate ranked list on open
  if (sortedStudents.length === 0) {
    generateRankedList()
  }

  const rankedStudents = [...students]
    .sort((a, b) => b.totalPoints - a.totalPoints)
    .map((student, index) => ({
      ...student,
      rank: index + 1,
    }))

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <Card className="w-full max-w-4xl max-h-[90vh] overflow-y-auto">
        <CardHeader className="flex flex-row items-center justify-between sticky top-0 bg-white z-10">
          <div>
            <CardTitle>Merit List</CardTitle>
          </div>
          <Button variant="ghost" size="sm" onClick={onClose}>
            <X className="w-4 h-4" />
          </Button>
        </CardHeader>

        <CardContent className="space-y-6">
          {/* Summary Stats */}
          <div className="grid grid-cols-3 gap-4">
            <div className="bg-blue-50 p-4 rounded-lg">
              <p className="text-sm text-gray-600">Total Students</p>
              <p className="text-2xl font-bold text-blue-600">{students.length}</p>
            </div>
            <div className="bg-green-50 p-4 rounded-lg">
              <p className="text-sm text-gray-600">Highest Points</p>
              <p className="text-2xl font-bold text-green-600">{Math.max(...students.map((s) => s.totalPoints))}</p>
            </div>
            <div className="bg-purple-50 p-4 rounded-lg">
              <p className="text-sm text-gray-600">Average Points</p>
              <p className="text-2xl font-bold text-purple-600">
                {(students.reduce((sum, s) => sum + s.totalPoints, 0) / students.length).toFixed(1)}
              </p>
            </div>
          </div>

          {/* Merit List Table */}
          <div className="overflow-x-auto">
            <table className="w-full border-collapse">
              <thead>
                <tr className="bg-gray-100 border-b-2 border-gray-300">
                  <th className="px-4 py-3 text-left font-semibold text-sm">Rank</th>
                  <th className="px-4 py-3 text-left font-semibold text-sm">Student Name</th>
                  <th className="px-4 py-3 text-left font-semibold text-sm">Roll No</th>
                  <th className="px-4 py-3 text-left font-semibold text-sm">Course</th>
                  <th className="px-4 py-3 text-left font-semibold text-sm">Year</th>
                  <th className="px-4 py-3 text-center font-semibold text-sm">Points</th>
                </tr>
              </thead>
              <tbody>
                {rankedStudents.map((student) => (
                  <tr
                    key={student.id}
                    className={`border-b ${student.rank <= 3 ? "bg-yellow-50" : "hover:bg-gray-50"}`}
                  >
                    <td className="px-4 py-3">
                      {student.rank <= 3 ? (
                        <Badge
                          className={
                            student.rank === 1
                              ? "bg-yellow-400 text-black"
                              : student.rank === 2
                                ? "bg-gray-300 text-black"
                                : "bg-orange-400 text-black"
                          }
                        >
                          {student.rank}
                        </Badge>
                      ) : (
                        <span className="font-semibold text-gray-600">{student.rank}</span>
                      )}
                    </td>
                    <td className="px-4 py-3 font-medium text-gray-900">{student.name}</td>
                    <td className="px-4 py-3 text-gray-600">{student.rollNo}</td>
                    <td className="px-4 py-3 text-gray-600 text-sm">{student.course}</td>
                    <td className="px-4 py-3 text-gray-600 text-center">{student.year}</td>
                    <td className="px-4 py-3 text-center">
                      <span className="font-bold text-blue-600 text-lg">{student.totalPoints}</span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Export Options */}
          <div className="flex gap-3 pt-4 border-t">
            <Button onClick={handleExportPDF} className="flex-1 gap-2 bg-red-600 hover:bg-red-700">
              <Download className="w-4 h-4" />
              Export as PDF
            </Button>
            <Button onClick={handleExportCSV} className="flex-1 gap-2 bg-green-600 hover:bg-green-700">
              <Download className="w-4 h-4" />
              Export as CSV
            </Button>
            <Button onClick={onClose} variant="outline" className="flex-1 gap-2 bg-transparent">
              <X className="w-4 h-4" />
              Close
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
